# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anvil < Formula
  desc "This executable automatically cleans up old files outside the given compliance timeframes."
  homepage "https://github.com/clivewalkden/homebrew-taps"
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/clivewalkden/anvil/releases/download/v1.1.0/anvil_1.1.0_darwin_amd64.tar.gz"
      sha256 "9f862dcd5db2b5ba7cfd5719ac37de562021d75f40de08b8ba7ab989d08186a6"

      def install
        bin.install "anvil"
      end
    end
    on_arm do
      url "https://github.com/clivewalkden/anvil/releases/download/v1.1.0/anvil_1.1.0_darwin_arm64.tar.gz"
      sha256 "c8705d8e95d143e39c041d8850cf771591246cfd88651a87f78d1fb7d472171d"

      def install
        bin.install "anvil"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clivewalkden/anvil/releases/download/v1.1.0/anvil_1.1.0_linux_amd64.tar.gz"
        sha256 "6c24130776cfb63ea91202f6789c145946871cef1819e8a3cebcff83943c5d29"

        def install
          bin.install "anvil"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clivewalkden/anvil/releases/download/v1.1.0/anvil_1.1.0_linux_arm64.tar.gz"
        sha256 "8edbdbe69af4106b29abfeec54d2a07b63bee2ca9c024f3a3ab03f87d298b171"

        def install
          bin.install "anvil"
        end
      end
    end
  end
end
