# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anvil < Formula
  desc "This executable automatically cleans up old files outside the given compliance timeframes."
  homepage "https://github.com/clivewalkden/homebrew-taps"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/clivewalkden/anvil/releases/download/v1.0.0/anvil_1.0.0_darwin_amd64.tar.gz"
      sha256 "269501a8bd0246eb753975a893c1977bf5fcfd883ad3627bdb279ff657b8d7d1"

      def install
        bin.install "anvil"
      end
    end
    on_arm do
      url "https://github.com/clivewalkden/anvil/releases/download/v1.0.0/anvil_1.0.0_darwin_arm64.tar.gz"
      sha256 "30802f29ea548c704fdd23d7d4699d4554e3678b7f48a23366b531f7ac4cac48"

      def install
        bin.install "anvil"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clivewalkden/anvil/releases/download/v1.0.0/anvil_1.0.0_linux_amd64.tar.gz"
        sha256 "a3d9731f49eb73c189cd11335a50c847fb75944f2975845953843a39ef500062"

        def install
          bin.install "anvil"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clivewalkden/anvil/releases/download/v1.0.0/anvil_1.0.0_linux_arm64.tar.gz"
        sha256 "18df9bdfb43ef7529c9ffa4b6d2ba513769b9582d2247b0b2a6370cfa0b96f65"

        def install
          bin.install "anvil"
        end
      end
    end
  end
end
