# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubTokenLimit < Formula
  desc "This executable returns the number of requests remaining for the GitHub API. If there are no tokens left it gives the reset time."
  homepage "https://github.com/clivewalkden/homebrew-taps"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clivewalkden/go-github-token-limit/releases/download/v1.2.1/go-github-token-limit_1.2.1_darwin_amd64.tar.gz"
      sha256 "6b6ad345ea1dde5609627be15d43832bcf24d989908a1438f1ce4c158f13e78b"

      def install
        bin.install "github-token-limit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clivewalkden/go-github-token-limit/releases/download/v1.2.1/go-github-token-limit_1.2.1_darwin_arm64.tar.gz"
      sha256 "b35117106c3d59939e8101d7abfba2b1e8b7be2803064aab438a1d94aac6519a"

      def install
        bin.install "github-token-limit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clivewalkden/go-github-token-limit/releases/download/v1.2.1/go-github-token-limit_1.2.1_linux_arm64.tar.gz"
      sha256 "40b43b7257b5eab1c2ad6c9079bbe75b9c8ad1240b7de9fc04092392268af362"

      def install
        bin.install "github-token-limit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clivewalkden/go-github-token-limit/releases/download/v1.2.1/go-github-token-limit_1.2.1_linux_amd64.tar.gz"
      sha256 "8d8d94312c83e5fbecbd7d7ca8fcf20af25ed3adce3a8be57c2d5803ba55f034"

      def install
        bin.install "github-token-limit"
      end
    end
  end
end
