# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WasabiCleanup < Formula
  desc "This executable automatically cleans up old files outside the given compliance timeframes."
  homepage "https://github.com/clivewalkden/homebrew-taps"
  version "1.3.4"

  on_macos do
    on_intel do
      url "https://github.com/clivewalkden/go-wasabi-cleanup/releases/download/v1.3.4/go-wasabi-cleanup_1.3.4_darwin_amd64.tar.gz"
      sha256 "bf936c1973865f2abba8d4c07b6a7b1264732102d21a68be394ae953884c387c"

      def install
        bin.install "wasabi-cleanup"
      end
    end
    on_arm do
      url "https://github.com/clivewalkden/go-wasabi-cleanup/releases/download/v1.3.4/go-wasabi-cleanup_1.3.4_darwin_arm64.tar.gz"
      sha256 "840254657b6d84619704ea486fcac4fae121d0b6aa86d4f8ffb70a0036c77ef7"

      def install
        bin.install "wasabi-cleanup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clivewalkden/go-wasabi-cleanup/releases/download/v1.3.4/go-wasabi-cleanup_1.3.4_linux_amd64.tar.gz"
        sha256 "cb21f81d9c9ee7c40878ed44a0ac8af77294abbabfe7c7974f1ca39fb4eefb89"

        def install
          bin.install "wasabi-cleanup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clivewalkden/go-wasabi-cleanup/releases/download/v1.3.4/go-wasabi-cleanup_1.3.4_linux_arm64.tar.gz"
        sha256 "76b2e7959957e4ee0639fc2cafe352c9bb8454e755293e1193a9a87fac39ec68"

        def install
          bin.install "wasabi-cleanup"
        end
      end
    end
  end
end
