# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WasabiCleanup < Formula
    desc "This executable automatically cleans up old files outside the given compliance timeframes."
    homepage "https://github.com/clivewalkden/homebrew-taps"
    version "1.3.3"
  
    on_macos do
      on_intel do
        url "https://github.com/clivewalkden/go-wasabi-cleanup/releases/download/v1.3.3/go-wasabi-cleanup_1.3.3_darwin_amd64.tar.gz"
        sha256 "0f1fe08ee51968870d51e9c7ad947518cfd5afa73c0ba183afb0fa2e09624396"
  
        def install
          bin.install "wasabi-cleanup"
        end
      end
      on_arm do
        url "https://github.com/clivewalkden/go-wasabi-cleanup/releases/download/v1.3.3/go-wasabi-cleanup_1.3.3_darwin_arm64.tar.gz"
        sha256 "312a84aaa407cdec323f980c1bac2601fbc2a3d12da238a845ebce2e94c55cb4"
  
        def install
          bin.install "wasabi-cleanup"
        end
      end
    end
  
    on_linux do
      on_intel do
        if Hardware::CPU.is_64_bit?
          url "https://github.com/clivewalkden/go-wasabi-cleanup/releases/download/v1.3.3/go-wasabi-cleanup_1.3.3_linux_amd64.tar.gz"
          sha256 "da1bd6edfacb77bfbb1655b02958f41f99d133acfebd54d0d5b8b53183fe7ef2"
  
          def install
            bin.install "wasabi-cleanup"
          end
        end
      end
      on_arm do
        if Hardware::CPU.is_64_bit?
          url "https://github.com/clivewalkden/go-wasabi-cleanup/releases/download/v1.3.3/go-wasabi-cleanup_1.3.3_linux_arm64.tar.gz"
          sha256 "1fbc410ad1e01b5d25dbc40197afb7955cf6c8314cffabb91022cf9203753503"
  
          def install
            bin.install "wasabi-cleanup"
          end
        end
      end
    end
  end
  