# This file was generated by GoReleaser. DO NOT EDIT.
cask "anvil" do
  desc "This executable automatically cleans up old files outside the given compliance timeframes."
  homepage "https://github.com/clivewalkden/homebrew-taps"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anvil"

  on_macos do
    on_intel do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v1.2.1/anvil-cli_1.2.1_darwin_amd64.tar.gz"
      sha256 "3ff17888fc26c1f1c8341120ff2555e34c3d13c176f93ad37146f486b04aff19"
    end
    on_arm do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v1.2.1/anvil-cli_1.2.1_darwin_arm64.tar.gz"
      sha256 "82a4ac84f7c12ab43cbcf499134e1d08484d91a37c5235d546817b7d7249d03f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v1.2.1/anvil-cli_1.2.1_linux_amd64.tar.gz"
      sha256 "97dd16445e546d5a5405034c7b635fc572cb8be78a3feb53445b6e6bfc150b38"
    end
    on_arm do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v1.2.1/anvil-cli_1.2.1_linux_arm64.tar.gz"
      sha256 "659c90e9e0d4f1e7b1c9ff6768368dbeabf2ce92123fdaf22e4d40849b4a1d7d"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'anvil' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/anvil"]
    end
  end

  # No zap stanza required
end
