# This file was generated by GoReleaser. DO NOT EDIT.
cask "anvil" do
  version "1.11.1"

  on_macos do
    on_intel do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v#{version}/anvil-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "d194910ebdd7b824a7e454c6f05fe60c6410fed1e64f0c33f6ca0dfa2ec08cf5"
    end
    on_arm do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v#{version}/anvil-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "063dd66193008105428377ee8479ba00fe10d8bc022027d369600f4d63e38c58"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v#{version}/anvil-cli_#{version}_linux_amd64.tar.gz"
      sha256 "823b41c81116428aa91e085b4612f255af1ee7f8ea80686996d282c4c01d3931"
    end
    on_arm do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v#{version}/anvil-cli_#{version}_linux_arm64.tar.gz"
      sha256 "e704ff7884337acbc4e64b906fecf3e7eeeff9456846cb05962651ccfd291320"
    end
  end

  name "anvil"
  desc "Anvil is a CLI tool that manages Magento Docker environments, syncing templates and wrapping docker compose for Magento-specific workflows."
  homepage "https://github.com/clivewalkden/homebrew-taps"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anvil"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'anvil' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/anvil"]
    end
  end

  # No zap stanza required

end
