# This file was generated by GoReleaser. DO NOT EDIT.
cask "anvil" do
  version "1.11.0"

  on_macos do
    on_intel do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v#{version}/anvil-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "14278eb77c95beb5cc7a22ff8176f99eecdc15e52651b010a4a4531ce19c92df"
    end
    on_arm do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v#{version}/anvil-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "08f2f1de01a308bfadba7736eadd70d86ed639890d31092959204af6077423eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v#{version}/anvil-cli_#{version}_linux_amd64.tar.gz"
      sha256 "a129ba21d265643fe842b2a47afe1b72fab5ecb085e77e1e9a47583281e064ad"
    end
    on_arm do
      url "https://github.com/clivewalkden/anvil-cli/releases/download/v#{version}/anvil-cli_#{version}_linux_arm64.tar.gz"
      sha256 "cd96eeb8660a6c82f2d741dc5008a025cfdd282d32d11928a742b92bc60a2508"
    end
  end

  name "anvil"
  desc "Anvil is a CLI tool that manages Magento Docker environments, syncing templates and wrapping docker compose for Magento-specific workflows."
  homepage "https://github.com/clivewalkden/homebrew-taps"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anvil"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'anvil' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/anvil"]
    end
  end

  # No zap stanza required

end
