# This file was generated by GoReleaser. DO NOT EDIT.
cask "flux" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "3eb40b26356acab79f574293dd7d13d6f6bd920e5ccd991c9003dacda4e3ec25"
      url "https://github.com/clivewalkden/flux-cli/releases/download/v#{version}/flux-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ed54b54b5749ca045437029aab831829d55e69ab7b03ce3256465aff7f0b75c"
      url "https://github.com/clivewalkden/flux-cli/releases/download/v#{version}/flux-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4ad55279e5aab0f44608f0737babd9bc59eff7feb34dec588c8a9ce3679d84a1"
      url "https://github.com/clivewalkden/flux-cli/releases/download/v#{version}/flux-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5939032aac652cc3cffc80f0c25cf85bf42b1eea070712041db7f4a671c18cb5"
      url "https://github.com/clivewalkden/flux-cli/releases/download/v#{version}/flux-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flux"
  desc "Magento patch config cleaner that removes ignored ece-patches entries from .magento.env.yaml."
  homepage "https://github.com/clivewalkden/homebrew-taps"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flux"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'flux' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flux"]
    end
  end

  # No zap stanza required
end
