# This file was generated by GoReleaser. DO NOT EDIT.
cask "flux" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "25431a5d5c4ffe9dc1af93e44a58ea244ee21dfc05a7f55df2a9a12bca5723f0"
      url "https://github.com/clivewalkden/flux-cli/releases/download/v#{version}/flux-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aedad6159e5c3417b401e88b4b6cac98d1fee01136df5c51da0e64de8c121d7f"
      url "https://github.com/clivewalkden/flux-cli/releases/download/v#{version}/flux-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e9a1150e042fbdcd6b3cbabb7aea4eb5d2f52164fa40ca7146ef329cd41eceb"
      url "https://github.com/clivewalkden/flux-cli/releases/download/v#{version}/flux-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ddb994859b0050dcc5d90a846427d9f9e4ed92286c794e6264b26c84ceed9d7"
      url "https://github.com/clivewalkden/flux-cli/releases/download/v#{version}/flux-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flux"
  desc "This executable automatically cleans up old files outside the given compliance timeframes."
  homepage "https://github.com/clivewalkden/homebrew-taps"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flux"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'flux' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flux"]
    end
  end

  # No zap stanza required

end
