# This file was generated by GoReleaser. DO NOT EDIT.
cask "flux" do
  desc "This executable automatically cleans up old files outside the given compliance timeframes."
  homepage "https://github.com/clivewalkden/homebrew-taps"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flux"

  on_macos do
    on_intel do
      url "https://github.com/clivewalkden/flux-cli/releases/download/v0.1.0/flux-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "c90106a5d07400b7663eab64f40bd36fbce0d6b5c065ffbe7844294765e30d5a"
    end
    on_arm do
      url "https://github.com/clivewalkden/flux-cli/releases/download/v0.1.0/flux-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "c977e05deafa3db4e37c68da4e4a811648916591aedcfa200f971d918708033d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clivewalkden/flux-cli/releases/download/v0.1.0/flux-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "4a14adc70e3f60b533fa85cba236cb7325e647982543563e15acacb61bad565e"
    end
    on_arm do
      url "https://github.com/clivewalkden/flux-cli/releases/download/v0.1.0/flux-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "6e7d6528bdcf869fc68779849c463fc5646bd2eba3681407c9b509a17408d333"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'flux' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flux"]
    end
  end

  # No zap stanza required
end
