# This file was generated by GoReleaser. DO NOT EDIT.
cask "github-token-limit" do
  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "638c41e7853d2e8deb81432d206c81a4799b0bad6fda485e21961d4b08d530c0"
      url "https://github.com/clivewalkden/go-github-token-limit/releases/download/v#{version}/github-token-limit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "60021463517be1bca45d09cf706f48dc0666b47d054006507a20af0c487b88ba"
      url "https://github.com/clivewalkden/go-github-token-limit/releases/download/v#{version}/github-token-limit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c78e7ff921cf957477647870b6f99f9224e37db9a286842db6b6daa1112ae741"
      url "https://github.com/clivewalkden/go-github-token-limit/releases/download/v#{version}/github-token-limit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d7e0966a0bae611b743f471c1a6194d81e1e54a09f05f150a70e492ac55406d"
      url "https://github.com/clivewalkden/go-github-token-limit/releases/download/v#{version}/github-token-limit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "github-token-limit"
  desc "This executable returns the number of requests remaining for the GitHub API. If there are no tokens left it gives the reset time."
  homepage "https://github.com/clivewalkden/homebrew-taps"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "github-token-limit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/github-token-limit"]
    end
  end

  # No zap stanza required
end
