# This file was generated by GoReleaser. DO NOT EDIT.
cask "magento-checker" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "1e7dace187aa739a2a4e0c65ef7126c96c40f5f44cc9191fb67c2c4c0fb8c605"
      url "https://github.com/clivewalkden/magento-checker-cli/releases/download/v#{version}/magento-checker_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f813e4e8f2e87ce55b4655a91ca13cb8ef216b69c0dbf287cff44436982e62bc"
      url "https://github.com/clivewalkden/magento-checker-cli/releases/download/v#{version}/magento-checker_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af59c825b51cfd8dffbe9a29befbaaf5c91373f68df82cf1419af0ed0dd1a8c0"
      url "https://github.com/clivewalkden/magento-checker-cli/releases/download/v#{version}/magento-checker_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e81b154b5b40284a6f8571b8f30b09001ae9819fac4393040b0b5216df2c68e"
      url "https://github.com/clivewalkden/magento-checker-cli/releases/download/v#{version}/magento-checker_#{version}_linux_arm64.tar.gz"
    end
  end

  name "magento-checker"
  desc "A command-line tool that verifies a Magento 2 project meets required infrastructure and security criteria. Checks are modular and easy to extend — adding a new check is a matter of implementing one interface and calling `Register()` in an `init()` function."
  homepage "https://github.com/clivewalkden/homebrew-taps"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "magento-checker"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'magento-checker' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/magento-checker"]
    end
  end

  # No zap stanza required

end
