# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo2txt" do
  name "repo2txt"
  desc "Convert a repository into a single text document for LLM consumption."
  homepage "https://github.com/clivewalkden/homebrew-taps"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo2txt"

  on_macos do
    on_intel do
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "7aed0f59660e11048d0cbfae2aed88633aff80b36c1b95f4aa5339c87fa42d38"
    end
    on_arm do
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "d3978bc6120c38d3ae455fb0d380ac3687141515428acf3aef2f8c6c86bea02f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_linux_amd64.tar.gz"
      sha256 "2043eadc666d750d3023390492c485a1dde0d7046911ce2009584f4cd61f1532"
    end
    on_arm do
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_linux_arm64.tar.gz"
      sha256 "b65fb2db4763e80d82d7a1c6fec658633c8fba2fb999f190b7961c8b9455e535"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repo2txt"]
    end
  end

  # No zap stanza required
end
