# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo2txt" do
  name "repo2txt"
  desc "Convert a repository into a single text document for LLM consumption."
  homepage "https://github.com/clivewalkden/homebrew-taps"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo2txt"

  on_macos do
    on_intel do
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "bd7bec14c1f7108fe79add040be2e7b408a21f19dd792236f045f6dc3350ad49"
    end
    on_arm do
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "1a47b16e0785a6287fa5e829f836438b6fa891e3896eaaacca0b077c724c664e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_linux_amd64.tar.gz"
      sha256 "727146684ee809353c7567872b0cc0287d8528fdc5c56614b9868c3fe661de84"
    end
    on_arm do
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_linux_arm64.tar.gz"
      sha256 "2ebf19d37168f2f819e599eb0aa1bbcd0b2848c43e36d19538423d589d33b86c"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repo2txt"]
    end
  end

  # No zap stanza required
end
