# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo2txt" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "3d8e1be24429f8105c35e7d5ea18e7f697c610c4023ec69ccb839c483b58ec64"
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0fd69934415d9f1cb0292ae16608294517558940fbd2e29a1cfe0326eb89b44"
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5636218b4b25391d2cc2b8635c430eed68b19a30f17b90bd8e7c73d96c01fded"
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "992c4c2dbb49cdf3ae516050d579e62bc80a9bdf919aeae866001128568c9d70"
      url "https://github.com/clivewalkden/repo2txt-cli/releases/download/v#{version}/repo2txt-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repo2txt"
  desc "Convert a repository into a single text document for LLM consumption."
  homepage "https://github.com/clivewalkden/homebrew-taps"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo2txt"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repo2txt"]
    end
  end

  # No zap stanza required

end
